# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tGyDCbr5qiaIFPIqlsCjTHJx6YfoTN_d
"""

from scipy.optimize import linprog
obj=[-50,-120]
lhs_ieq=[[7000,2000],[10,30]]
rhs_ieq=[700000,1200]
bnd=[(0,float("inf")),(0,float("inf"))]
opt=linprog(c=obj,A_ub=lhs_ieq,b_ub=rhs_ieq,bounds=bnd,method="Simplex")
opt